name: Build and deploy Node.js app to Azure Web App - college-baseball-stats-site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      ACTIONS_STEP_DEBUG: true # Enable additional debug logging

    steps:
      - uses: actions/checkout@v4

      - name: Print System Information
        run: |
          echo "Printing system information..."
          systeminfo

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.*'

      - name: npm install and build for Node.js server
        run: |
          npm install
          npm run build
          npm run test --if-present

      - name: npm install and build for React app
        run: |
          cd college-baseball-app
          npm install
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: |
            dist/bundle.js
            node.mjs
            package.json
            college-baseball-app/dist/**
            web.config

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'college-baseball-stats-site'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E351DECC20394D40BD73DF0EB9634B72 }}
          package: .
